from siebenapp import *

# Some real-world example, with cleaned goal names
EXAMPLE = RenderResult(
    rows=[
        RenderRow(
            goal_id=1,
            raw_id=1,
            name="node 1",
            is_open=True,
            is_switchable=False,
            edges=[
                (2, EdgeType.PARENT),
                (3, EdgeType.PARENT),
                (4, EdgeType.PARENT),
                (5, EdgeType.PARENT),
                (40, EdgeType.PARENT),
            ],
            attrs={},
        ),
        RenderRow(
            goal_id=2,
            raw_id=2,
            name="node 2",
            is_open=True,
            is_switchable=True,
            edges=[(43, EdgeType.PARENT), (44, EdgeType.PARENT)],
            attrs={},
        ),
        RenderRow(
            goal_id=3,
            raw_id=3,
            name="node 3",
            is_open=True,
            is_switchable=False,
            edges=[
                (6, EdgeType.BLOCKER),
                (7, EdgeType.BLOCKER),
                (8, EdgeType.BLOCKER),
                (30, EdgeType.PARENT),
                (37, EdgeType.PARENT),
            ],
            attrs={},
        ),
        RenderRow(
            goal_id=4,
            raw_id=4,
            name="node 4",
            is_open=True,
            is_switchable=True,
            edges=[],
            attrs={},
        ),
        RenderRow(
            goal_id=5,
            raw_id=5,
            name="node 5",
            is_open=True,
            is_switchable=False,
            edges=[(6, EdgeType.PARENT), (7, EdgeType.PARENT), (8, EdgeType.PARENT)],
            attrs={},
        ),
        RenderRow(
            goal_id=6,
            raw_id=6,
            name="node 6",
            is_open=True,
            is_switchable=True,
            edges=[],
            attrs={},
        ),
        RenderRow(
            goal_id=7,
            raw_id=7,
            name="node 7",
            is_open=True,
            is_switchable=False,
            edges=[(9, EdgeType.BLOCKER), (16, EdgeType.BLOCKER)],
            attrs={},
        ),
        RenderRow(
            goal_id=8,
            raw_id=8,
            name="node 8",
            is_open=False,
            is_switchable=True,
            edges=[],
            attrs={},
        ),
        RenderRow(
            goal_id=9,
            raw_id=9,
            name="node 9",
            is_open=True,
            is_switchable=False,
            edges=[
                (10, EdgeType.PARENT),
                (11, EdgeType.PARENT),
                (12, EdgeType.PARENT),
                (13, EdgeType.PARENT),
                (14, EdgeType.PARENT),
                (15, EdgeType.PARENT),
            ],
            attrs={},
        ),
        RenderRow(
            goal_id=10,
            raw_id=10,
            name="node 10",
            is_open=False,
            is_switchable=True,
            edges=[(51, EdgeType.BLOCKER)],
            attrs={},
        ),
        RenderRow(
            goal_id=11,
            raw_id=11,
            name="node 11",
            is_open=False,
            is_switchable=True,
            edges=[(51, EdgeType.PARENT)],
            attrs={},
        ),
        RenderRow(
            goal_id=12,
            raw_id=12,
            name="node 12",
            is_open=False,
            is_switchable=True,
            edges=[(51, EdgeType.BLOCKER)],
            attrs={},
        ),
        RenderRow(
            goal_id=13,
            raw_id=13,
            name="node 13",
            is_open=False,
            is_switchable=True,
            edges=[(51, EdgeType.BLOCKER)],
            attrs={},
        ),
        RenderRow(
            goal_id=14,
            raw_id=14,
            name="node 14",
            is_open=False,
            is_switchable=True,
            edges=[(51, EdgeType.BLOCKER)],
            attrs={},
        ),
        RenderRow(
            goal_id=15,
            raw_id=15,
            name="node 15",
            is_open=True,
            is_switchable=True,
            edges=[(51, EdgeType.BLOCKER)],
            attrs={},
        ),
        RenderRow(
            goal_id=16,
            raw_id=16,
            name="node 16",
            is_open=False,
            is_switchable=True,
            edges=[
                (17, EdgeType.PARENT),
                (18, EdgeType.PARENT),
                (19, EdgeType.PARENT),
                (20, EdgeType.PARENT),
                (24, EdgeType.PARENT),
                (25, EdgeType.PARENT),
                (26, EdgeType.PARENT),
                (27, EdgeType.PARENT),
            ],
            attrs={},
        ),
        RenderRow(
            goal_id=17,
            raw_id=17,
            name="node 17",
            is_open=False,
            is_switchable=False,
            edges=[],
            attrs={},
        ),
        RenderRow(
            goal_id=18,
            raw_id=18,
            name="node 18",
            is_open=False,
            is_switchable=False,
            edges=[(23, EdgeType.PARENT)],
            attrs={},
        ),
        RenderRow(
            goal_id=19,
            raw_id=19,
            name="node 19",
            is_open=False,
            is_switchable=False,
            edges=[(21, EdgeType.BLOCKER)],
            attrs={},
        ),
        RenderRow(
            goal_id=20,
            raw_id=20,
            name="node 20",
            is_open=False,
            is_switchable=False,
            edges=[(21, EdgeType.PARENT), (22, EdgeType.PARENT)],
            attrs={},
        ),
        RenderRow(
            goal_id=21,
            raw_id=21,
            name="node 21",
            is_open=False,
            is_switchable=False,
            edges=[(38, EdgeType.BLOCKER)],
            attrs={},
        ),
        RenderRow(
            goal_id=22,
            raw_id=22,
            name="node 22",
            is_open=False,
            is_switchable=False,
            edges=[],
            attrs={},
        ),
        RenderRow(
            goal_id=23,
            raw_id=23,
            name="node 23",
            is_open=False,
            is_switchable=False,
            edges=[(38, EdgeType.PARENT)],
            attrs={},
        ),
        RenderRow(
            goal_id=24,
            raw_id=24,
            name="node 24",
            is_open=False,
            is_switchable=False,
            edges=[(18, EdgeType.BLOCKER)],
            attrs={},
        ),
        RenderRow(
            goal_id=25,
            raw_id=25,
            name="node 25",
            is_open=False,
            is_switchable=False,
            edges=[(18, EdgeType.BLOCKER)],
            attrs={},
        ),
        RenderRow(
            goal_id=26,
            raw_id=26,
            name="node 26",
            is_open=False,
            is_switchable=False,
            edges=[(18, EdgeType.BLOCKER)],
            attrs={},
        ),
        RenderRow(
            goal_id=27,
            raw_id=27,
            name="node 27",
            is_open=False,
            is_switchable=False,
            edges=[(18, EdgeType.BLOCKER)],
            attrs={},
        ),
        RenderRow(
            goal_id=28,
            raw_id=28,
            name="node 28",
            is_open=False,
            is_switchable=True,
            edges=[(29, EdgeType.PARENT)],
            attrs={},
        ),
        RenderRow(
            goal_id=29,
            raw_id=29,
            name="node 29",
            is_open=False,
            is_switchable=False,
            edges=[(45, EdgeType.PARENT)],
            attrs={},
        ),
        RenderRow(
            goal_id=30,
            raw_id=30,
            name="node 30",
            is_open=True,
            is_switchable=True,
            edges=[
                (31, EdgeType.PARENT),
                (32, EdgeType.PARENT),
                (33, EdgeType.PARENT),
                (34, EdgeType.PARENT),
                (35, EdgeType.PARENT),
                (36, EdgeType.PARENT),
            ],
            attrs={},
        ),
        RenderRow(
            goal_id=31,
            raw_id=31,
            name="node 31",
            is_open=False,
            is_switchable=True,
            edges=[],
            attrs={},
        ),
        RenderRow(
            goal_id=32,
            raw_id=32,
            name="node 32",
            is_open=False,
            is_switchable=True,
            edges=[],
            attrs={},
        ),
        RenderRow(
            goal_id=33,
            raw_id=33,
            name="node 33",
            is_open=False,
            is_switchable=True,
            edges=[],
            attrs={},
        ),
        RenderRow(
            goal_id=34,
            raw_id=34,
            name="node 34",
            is_open=False,
            is_switchable=True,
            edges=[],
            attrs={},
        ),
        RenderRow(
            goal_id=35,
            raw_id=35,
            name="node 35",
            is_open=False,
            is_switchable=True,
            edges=[],
            attrs={},
        ),
        RenderRow(
            goal_id=36,
            raw_id=36,
            name="node 36",
            is_open=False,
            is_switchable=True,
            edges=[],
            attrs={},
        ),
        RenderRow(
            goal_id=37,
            raw_id=37,
            name="node 37",
            is_open=True,
            is_switchable=False,
            edges=[
                (9, EdgeType.PARENT),
                (16, EdgeType.PARENT),
                (28, EdgeType.PARENT),
                (42, EdgeType.PARENT),
                (46, EdgeType.PARENT),
            ],
            attrs={},
        ),
        RenderRow(
            goal_id=38,
            raw_id=38,
            name="node 38",
            is_open=False,
            is_switchable=False,
            edges=[],
            attrs={},
        ),
        RenderRow(
            goal_id=39,
            raw_id=39,
            name="node 39",
            is_open=False,
            is_switchable=True,
            edges=[],
            attrs={},
        ),
        RenderRow(
            goal_id=40,
            raw_id=40,
            name="node 40",
            is_open=True,
            is_switchable=False,
            edges=[(39, EdgeType.PARENT), (41, EdgeType.BLOCKER)],
            attrs={},
        ),
        RenderRow(
            goal_id=41,
            raw_id=41,
            name="node 41",
            is_open=True,
            is_switchable=True,
            edges=[],
            attrs={},
        ),
        RenderRow(
            goal_id=42,
            raw_id=42,
            name="node 42",
            is_open=False,
            is_switchable=True,
            edges=[
                (43, EdgeType.BLOCKER),
                (44, EdgeType.BLOCKER),
                (49, EdgeType.PARENT),
            ],
            attrs={},
        ),
        RenderRow(
            goal_id=43,
            raw_id=43,
            name="node 43",
            is_open=False,
            is_switchable=False,
            edges=[],
            attrs={},
        ),
        RenderRow(
            goal_id=44,
            raw_id=44,
            name="node 44",
            is_open=False,
            is_switchable=False,
            edges=[],
            attrs={},
        ),
        RenderRow(
            goal_id=45,
            raw_id=45,
            name="node 45",
            is_open=False,
            is_switchable=False,
            edges=[],
            attrs={},
        ),
        RenderRow(
            goal_id=46,
            raw_id=46,
            name="node 46",
            is_open=False,
            is_switchable=True,
            edges=[(47, EdgeType.PARENT), (48, EdgeType.PARENT)],
            attrs={},
        ),
        RenderRow(
            goal_id=47,
            raw_id=47,
            name="node 47",
            is_open=False,
            is_switchable=False,
            edges=[],
            attrs={},
        ),
        RenderRow(
            goal_id=48,
            raw_id=48,
            name="node 48",
            is_open=False,
            is_switchable=False,
            edges=[],
            attrs={},
        ),
        RenderRow(
            goal_id=49,
            raw_id=49,
            name="node 49",
            is_open=False,
            is_switchable=False,
            edges=[(50, EdgeType.PARENT)],
            attrs={},
        ),
        RenderRow(
            goal_id=50,
            raw_id=50,
            name="node 50",
            is_open=False,
            is_switchable=False,
            edges=[],
            attrs={},
        ),
        RenderRow(
            goal_id=51,
            raw_id=51,
            name="node 51",
            is_open=False,
            is_switchable=False,
            edges=[],
            attrs={},
        ),
    ],
    select=(1, 1),
    roots={1},
    node_opts={
        1: {},
        2: {},
        3: {},
        4: {},
        5: {},
        6: {},
        7: {},
        8: {},
        9: {},
        10: {},
        11: {},
        12: {},
        13: {},
        14: {},
        15: {},
        16: {},
        17: {},
        18: {},
        19: {},
        20: {},
        21: {},
        22: {},
        23: {},
        24: {},
        25: {},
        26: {},
        27: {},
        28: {},
        29: {},
        30: {},
        31: {},
        32: {},
        33: {},
        34: {},
        35: {},
        36: {},
        37: {},
        38: {},
        39: {},
        40: {},
        41: {},
        42: {},
        43: {},
        44: {},
        45: {},
        46: {},
        47: {},
        48: {},
        49: {},
        50: {},
        51: {},
    },
)
